apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello-container
          image: harbor.vmw.local/library/hello@sha256:df322a55c16c024aeefaa7ba2cb37cdc92a553194935970291a88942337aa31d