apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Container port
  type: LoadBalancer